### ISSUE TITLE
Using controller

### ISSUE THREAD

**Issue by zzyzzyzzx** [rockhopsoft/survloop#1]
Hello,

so i implemented your bundle and it took over pointing to all your stuff, which broke my system, so im trying to combine both mine and your stuff, and the issue im having is that i cant seem to 'use' your auth controller from one of my controllers, meaning i can not have my members edit their profiles because its trying to pull your auth data but failing, any suggestions?

**Comment by rockhopsoft** [comment]
Hi, So sorry to hear it's caused trouble. I'm not sure how it would interact with existing systems running other packages. Perhaps the damage could be undone by swapping out the SurvLoop user model in config/auth.php , reverting to 'model' => App\User::class . Maybe you'll need to reverse the rest of the install process too?

Do you have any suggestions on how to advise other people that SurvLoop is currently intended to be a standalone system atop of Laravel? Thanks so much!

**Comment by zzyzzyzzx** [comment]
its really not an issue, i was just looking for something wiki based for a backend, im going to redo my site using your system, and see if i can integrate it correctly, and not try to hack and slash everything together

**Comment by rockhopsoft** [comment]
Oh cool. :) This is not wiki based software in the sense of WikiMedia. This is a database design and survey generation system, though I think it will increasingly be a flexible tool to solve many problems. I plan to provide more documentation in the coming weeks. Thank you for your interest and patience!

Here's the best live demo of one it's end results: https://app.openpolice.org:8443/test
Among other methods, the resulting data can also be provided as XML included an automatically generated schema, eg.
https://app.openpolice.org:8443/xml-schema
https://app.openpolice.org:8443/xml-example

It might be worth peaking around for examples of how to extend the engine for your needs. Sorry there's not more documentation yet! <3
